trigger:
  branches:
    include:
      - release/qa

pool:
  name: Default
  demands:
    - Agent.Name -equals AZWSVDOP101

steps:
- checkout: self
  persistCredentials: true
  fetchTags: true

- powershell: |
    git config user.name "Azure DevOps"
    git config user.email "devops@yourcompany.com"

    # Fetch tags
    git fetch --tags

    # Get the latest tag matching the pattern 'qa-X.Y.Z'
    $latestTag = git tag --list "qa-*" | Sort-Object {
      ($_ -replace '^qa-', '') -as [version]
    } | Select-Object -Last 1

    Write-Host "Latest tag found: $latestTag"

    if (-not $latestTag) {
      $newTag = "qa-1.0.0"
    }
    else {
      $ver = [version]($latestTag -replace '^qa-', '')
      $newVer = "{0}.{1}.{2}" -f $ver.Major, $ver.Minor, ($ver.Build + 1)
      $newTag = "qa-$newVer"
    }

    Write-Host "Creating new tag: $newTag"
    git tag -a $newTag -m "Auto-tagged release: $newTag"
    git push origin $newTag

    Write-Host "##vso[task.setvariable variable=newTag]$newTag"
  displayName: 'Auto-Increment and Push Tag'







